#!/bin/bash

# Auto-generated script to install packages
sudo apt install -y amd
sudo apt install -y amd
sudo apt install -y comgr
sudo apt install -y comgr5
sudo apt install -y half
sudo apt install -y half5
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hip
sudo apt install -y hipblas
sudo apt install -y hipblas
sudo apt install -y hipblas
sudo apt install -y hipblas5
sudo apt install -y hipblaslt
sudo apt install -y hipblaslt
sudo apt install -y hipblaslt
sudo apt install -y hipblaslt5
sudo apt install -y hipcc
sudo apt install -y hipcc5
sudo apt install -y hipcub
sudo apt install -y hipcub
sudo apt install -y hipfft
sudo apt install -y hipfft
sudo apt install -y hipfft
sudo apt install -y hipfft5
sudo apt install -y hipfort
sudo apt install -y hipfort
sudo apt install -y hipify
sudo apt install -y hipify
sudo apt install -y hipsolver
sudo apt install -y hipsolver
sudo apt install -y hipsolver
sudo apt install -y hipsolver5
sudo apt install -y hipsparse
sudo apt install -y hipsparse
sudo apt install -y hipsparse
sudo apt install -y hipsparse5
sudo apt install -y hsa
sudo apt install -y hsa
sudo apt install -y hsa
sudo apt install -y hsa
sudo apt install -y hsa
sudo apt install -y hsa
sudo apt install -y hsakmt
sudo apt install -y hsakmt
sudo apt install -y migraphx
sudo apt install -y migraphx
sudo apt install -y migraphx
sudo apt install -y migraphx5
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y miopen
sudo apt install -y mivisionx
sudo apt install -y mivisionx5
sudo apt install -y openmp
sudo apt install -y openmp
sudo apt install -y openmp
sudo apt install -y openmp
sudo apt install -y rccl
sudo apt install -y rccl
sudo apt install -y rccl
sudo apt install -y rccl
sudo apt install -y rccl
sudo apt install -y rccl5
sudo apt install -y rdc
sudo apt install -y rdc5
sudo apt install -y rocalution
sudo apt install -y rocalution
sudo apt install -y rocalution
sudo apt install -y rocalution5
sudo apt install -y rocblas
sudo apt install -y rocblas
sudo apt install -y rocblas
sudo apt install -y rocblas5
sudo apt install -y rocfft
sudo apt install -y rocfft
sudo apt install -y rocfft
sudo apt install -y rocfft5
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocm
sudo apt install -y rocminfo
sudo apt install -y rocminfo5
sudo apt install -y rocprim
sudo apt install -y rocprim
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler
sudo apt install -y rocprofiler5
sudo apt install -y rocrand
sudo apt install -y rocrand
sudo apt install -y rocrand
sudo apt install -y rocrand5
sudo apt install -y rocsolver
sudo apt install -y rocsolver
sudo apt install -y rocsolver
sudo apt install -y rocsolver5
sudo apt install -y rocsparse
sudo apt install -y rocsparse
sudo apt install -y rocsparse
sudo apt install -y rocsparse5
sudo apt install -y rocthrust
sudo apt install -y rocthrust
sudo apt install -y roctracer
sudo apt install -y roctracer
sudo apt install -y roctracer
sudo apt install -y roctracer5
sudo apt install -y rocwmma
sudo apt install -y rocwmma
sudo apt install -y rocwmma
sudo apt install -y rocwmma
